### ISSUE TITLE
packages don't drop below the screen border anymore

### ISSUE THREAD

**Issue by drwuro** [ToolboxBodensee/unity_ghostgame#14]
this is due to the CircleCollider2D which got introduced in https://github.com/ToolboxBodensee/unity_ghostgame/commit/9c0d38438e9fd9d7afa0f38b7e281a7f5368a9eb

when this component is removed, everything works as expected. check whether the CircleCollider serves a real purpose, maybe it's possible to simply remove it again

**Comment by DEvil0000** [comment]
works for me now
