### ISSUE TITLE
weird package attachment can happen

### ISSUE THREAD

**Issue by drwuro** [ToolboxBodensee/unity_ghostgame#16]
during playtesting, this balloon was coming up:

![weirdballoon](https://user-images.githubusercontent.com/12046626/57192551-0554c400-6f32-11e9-990e-a7dc26e6bfcf.png)

**Comment by DEvil0000** [comment]
not sure how but i have seen that two.
I think others may be able to push it in and then its stuck.

**Comment by DEvil0000** [comment]
i think thats also fixed with #15
